postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: little_books_<%= Rails.env %>
  min_messages: ERROR

development:
  adapter: postgresql
  encoding: UTF-8
  database: little_books_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: UTF-8
  database: little_books_test
  pool: 5
  host: localhost


production:
  adapter: postgresql
  encoding: UTF-8
  database: little_books_production
  pool: 5

